### ISSUE TITLE
Someone would like to play X, do you want to join?

### ISSUE THREAD

**Issue by SenneDeVocht** [nerdland-unofficial-fans/nerdlandbot#29] opened 2020-08-03 11:25 UTC
Users can subscribe to different roles (for instance "@gezelschapspelletjes" or "@videogames"). A user can then call the bot to say they would like to play a game, for instance CS:GO. The bot then sends a message to @videogames asking if anyone wants to join them.

**Comment by woutermeuwis** [comment] 2020-08-03 11:28
Duplicate of #4 

We decided to use lists, which are tracked by the bot, so we don't need to use roles.
This is because Jeroen prefers the bot to request as little permissions as possible

**Closed as completed by woutermeuwis** 2020-08-03 11:28 UTC
